M48
; DRILL file {KiCad (6.0.9-0)} date Monday, March 20, 2023 at 01:15:31 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-03-20T13:15:31-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.750
%
G90
G05
T1
X82.04Y-64.31
X82.04Y-113.32
X140.03Y-113.31
X140.04Y-64.33
T0
M30
